# Build Recurrent Neural Network (RNN)

In [4]:
# Import necessary libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding
# Import the Tokenizer class from the text module in TensorFlow Keras preprocessing
# This class is used to vectorize a text corpus, by turning each text into either a sequence of integers
# (each integer being the index of a token in a dictionary) or into a vector where the coefficient(s)
# for each token could be binary, based on word count, based on tf-idf...
from tensorflow.keras.preprocessing.text import Tokenizer
# Import the pad_sequences function from the sequence module in TensorFlow Keras preprocessing
# This function is used to ensure that all sequences in a list have the same length,
# by padding shorter sequences with a specified value (by default 0) or truncating longer sequences
# to a specified length.
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample Data for Training

In [5]:

# Sample data
sentences = [
    "I love pakistan"
    "Machine learning algorithms are powerful tools."
    "I enjoy exploring new algorithms."
    "Learning about AI is captivating."
    "Deep learning models can be complex."
    "I love understanding how neural networks work."
    "The field of data science is evolving rapidly."
    "I find artificial intelligence intriguing."
    "Studying computer vision is exciting."
    "Natural language processing is a fascinating domain."
    "I enjoy coding in Python for data science projects."
    "Building models is a creative process."
    "I love experimenting with different machine learning techniques."
    "The potential of AI to transform industries is amazing."
    "I enjoy staying updated with the latest tech trends."
    "Learning about reinforcement learning is interesting."
    "I find predictive modeling to be very useful."
    "I love solving problems with data analysis."
    "Data preprocessing is a crucial step in machine learning."
    "I enjoy reading research papers on deep learning."
    "I find optimization techniques fascinating."
    "Understanding algorithms helps in developing better solutions."
    "I love the challenge of debugging code."
    "Machine learning applications are diverse and impactful."
    "I enjoy collaborating with others on tech projects."
    "Learning new programming languages is fun."
    "I love working with large datasets."
    "I find feature engineering to be an art."
    "Model evaluation is an essential part of machine learning."
    "I enjoy attending tech conferences."
    "Learning about big data technologies is exciting."
    "I love experimenting with neural network architectures."
    "I find the theory behind machine learning algorithms interesting."
    "I enjoy visualizing data insights."
    "Machine learning models can make accurate predictions."
    "I love the creativity involved in data storytelling."
    "I find unsupervised learning techniques intriguing."
    "I enjoy automating tasks with AI."
    "Learning about AI ethics is important."
    "I love the problem-solving aspect of machine learning."
    "I find cloud computing technologies fascinating."
    "I enjoy using machine learning for real-world applications."
    "I love experimenting with different data preprocessing techniques."
    "I find transfer learning to be a powerful approach."
    "I enjoy working on machine learning projects."
    "Learning about data privacy is crucial."
    "I love the innovation happening in the AI field."
    "I find data visualization tools useful."
    "I enjoy testing and validating machine learning models."
    "I love discovering new machine learning applications."
    "I find ensemble methods to be effective."
    "I enjoy learning from data."
    "Machine learning can provide valuable insights."
    "I love the interdisciplinary nature of AI."
    "I find recommendation systems interesting."
    "I enjoy participating in hackathons."
    "Learning about neural networks is fascinating."
    "I love the potential of AI to solve complex problems."
    "I find sentiment analysis intriguing."
    "I enjoy implementing machine learning algorithms."
    "I love the excitement of discovering patterns in data."
    "I find time series analysis challenging."
    "I enjoy exploring different types of data."
    "Machine learning is transforming various industries."
    "I love working on predictive analytics."
    "I find anomaly detection to be useful."
    "I enjoy studying the mathematics behind machine learning."
    "I love the hands-on experience of building models."
    "I find clustering techniques interesting."
    "I enjoy exploring open-source machine learning libraries."
    "Machine learning can automate complex tasks."
    "I love the flexibility of machine learning models."
    "I find computer vision applications fascinating."
    "I enjoy solving real-world problems with AI."
    "I love the continuous learning aspect of AI."
    "I find reinforcement learning to be challenging."
    "I enjoy experimenting with hyperparameter tuning."
    "Machine learning can improve decision-making processes."
    "I love the creativity involved in feature selection."
    "I find generative models to be fascinating."
    "I enjoy reading about the latest AI advancements."
    "Machine learning can enhance user experiences."
    "I love the diversity of machine learning applications."
    "I find natural language generation intriguing."
    "I enjoy working with text data."
    "Machine learning can optimize business processes."
    "I love the innovation in AI research."
    "I find the concept of machine learning interpretability interesting."
    "I enjoy creating machine learning workflows."
    "Machine learning can uncover hidden patterns."
    "I love the impact of AI on society."
    "I find deep reinforcement learning fascinating."
    "I enjoy developing custom machine learning solutions."
    "Machine learning can improve customer experiences."
    "I love the potential of AI in healthcare."
    "I find the scalability of machine learning models intriguing."
    "I enjoy applying machine learning to finance."
    "Machine learning can enhance security measures."
    "I love the possibilities of AI in creative industries."
    "I find the ethical implications of AI important."
    "I enjoy sharing knowledge about machine learning."
    "This Free Advance AI Course that is helping alot of students to learn the concepts of AI and provides the detailed guideline on how to learn AI. This course enables the students to make their own projects. Updates them with the state of the art technologies and provide all the necessary knowlegde so that they should not be dependend on anyone to be able to learn anything."
]

# Tokenization and Preprocessing of Data

In [6]:
# Initialize the tokenizer
tokenizer = Tokenizer()

# Fit the tokenizer on the provided sentences
tokenizer.fit_on_texts(sentences)

# Get the total number of unique words (plus one for padding)
total_words = len(tokenizer.word_index) + 1
print(total_words)
print(tokenizer.word_index)

# Initialize a list to hold input sequences
input_sequences = []

# Iterate over each sentence
for line in sentences:
    # Convert the sentence to a sequence of integers
    token_list = tokenizer.texts_to_sequences([line])[0]
    # print(token_list)
    # Create n-gram sequences
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)




# Determine the maximum sequence length
max_sequence_len = max([len(x) for x in input_sequences])

# Pad sequences to ensure they are all the same length
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
print(input_sequences)


255
{'i': 1, 'learning': 2, 'the': 3, 'machine': 4, 'love': 5, 'enjoy': 6, 'find': 7, 'of': 8, 'ai': 9, 'is': 10, 'to': 11, 'data': 12, 'with': 13, 'in': 14, 'can': 15, 'be': 16, 'about': 17, 'models': 18, 'on': 19, 'fascinating': 20, 'algorithms': 21, 'intriguing': 22, 'techniques': 23, 'interesting': 24, 'applications': 25, 'a': 26, 'projects': 27, 'experimenting': 28, 'and': 29, 'working': 30, 'exploring': 31, 'new': 32, 'deep': 33, 'complex': 34, 'neural': 35, 'different': 36, 'potential': 37, 'industries': 38, 'tech': 39, 'reinforcement': 40, 'useful': 41, 'solving': 42, 'problems': 43, 'analysis': 44, 'technologies': 45, 'learn': 46, 'are': 47, 'powerful': 48, 'tools': 49, 'understanding': 50, 'how': 51, 'networks': 52, 'field': 53, 'science': 54, 'studying': 55, 'computer': 56, 'vision': 57, 'exciting': 58, 'natural': 59, 'language': 60, 'for': 61, 'building': 62, 'creative': 63, 'latest': 64, 'predictive': 65, 'preprocessing': 66, 'crucial': 67, 'reading': 68, 'research': 69, '

# Data Preparation:

In [7]:
# Split data into inputs and labels

# Inputs: All elements of the sequences except the last one
X = input_sequences[:, :-1]
print("Input Data: ", X)

# Labels : The last element of each sequence (the word to predict)
y = input_sequences[:, -1]
print("Labels: ", y)

# Convert labels to one-hot encoded format
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

Input Data:  [[  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   1   5]
 [  0   0   0 ...   1   5  98]
 ...
 [  0   0   1 ...  11  16 253]
 [  0   1   5 ...  16 253  11]
 [  1   5  98 ... 253  11  46]]
Labels:  [  5  98   2  21  47  48  49   1   6  31  32  21   2  17   9  10  99  33
   2  18  15  16  34   1   5  50  51  35  52 100   3  53   8  12  54  10
 101 102   1   7 103 104  22  55  56  57  10  58  59  60 105  10  26  20
 106   1   6 107  14 108  61  12  54  27  62  18  10  26  63 109   1   5
  28  13  36   4   2  23   3  37   8   9  11 110  38  10 111   1   6 112
 113  13   3  64  39 114   2  17  40   2  10  24   1   7  65 115  11  16
 116  41   1   5  42  43  13  12  44  12  66  10  26  67 117  14   4   2
   1   6  68  69 118  19  33   2   1   7 119  23  20  50  21 120  14  70
 121  71   1   5   3 122   8 123 124   4   2  25  47 125  29 126   1   6
 127  13 128  19  39  27   2  32 129 130  10 131   1   5  30  13 132 133
   1   7  72 134  11  16  73  74 135 136  10  73 137 138

# Defining the Model Architecture:

In [8]:
# Define the RNN model

# Sequential model allows stacking layers in a linear fashion
model = Sequential([
    # Embedding layer to convert word indices to dense vectors of fixed size
    # Input dimension: total number of words, Output dimension: size of embedding vectors
    # Input length: length of input sequences (excluding the last word)
    Embedding(total_words, 10, input_length=max_sequence_len-1),

    # SimpleRNN layer with 50 units, which processes the sequence data
    SimpleRNN(50),

    # Dense output layer with a softmax activation function
    # Output dimension: total number of words (for multi-class classification)
    Dense(total_words, activation='softmax')
])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
# Compile the modal
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
# Train the model
model.fit(X, y, epochs=50, verbose=1)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 7s 181ms/step - accuracy: 0.0038 - loss: 5.5341
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 6s 236ms/step - accuracy: 0.0265 - loss: 5.3446
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - accuracy: 0.0386 - loss: 4.9555
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 6s 259ms/step - accuracy: 0.0940 - loss: 4.6846
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 4s 178ms/step - accuracy: 0.0880 - loss: 4.6849
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 7s 278ms/step - accuracy: 0.0948 - loss: 4.5491
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 7s 272ms/step - accuracy: 0.0861 - loss: 4.6128
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 10s 284ms/step - accuracy: 0.0961 - loss: 4.6428
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - accuracy: 0.0981 - loss: 4.5833
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 7s 280ms/step - accuracy: 0.0871 - loss: 4.6280
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 5s 206ms/step - accuracy: 0.0871 - loss: 4.5653
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 7s 312ms/ste

# Next Word Prediction

In [9]:
# Function to predict the next word(s) given a seed text
def predict_next_word(seed_text, next_words=1):
    for _ in range(next_words):
        # Convert the seed text to a sequence of integers
        token_list = tokenizer.texts_to_sequences([seed_text])[0]

        # Pad the sequence to match the input length required by the model
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

        # Predict the probabilities of the next word in the sequence
        predicted = model.predict(token_list, verbose=0)

        # Get the index of the word with the highest probability
        predicted_word_index = np.argmax(predicted, axis=-1)[0]

        # Retrieve the word corresponding to the predicted index
        predicted_word = tokenizer.index_word[predicted_word_index]

        # Append the predicted word to the seed text
        seed_text += " " + predicted_word

    # Return the updated seed text with the predicted word(s)
    return seed_text


# Test the Prediction function with a sample input

In [10]:
print(predict_next_word("I love the"))

I love the ethical


# Building a Long Short-Term Memory (LSTM)

In [11]:
# Import necessary libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample Data

In [12]:

# Sample data
sentences = [
    "Machine learning algorithms are powerful tools."
    "I enjoy exploring new algorithms."
    "Learning about AI is captivating."
    "Deep learning models can be complex."
    "I love understanding how neural networks work."
    "The field of data science is evolving rapidly."
    "I find artificial intelligence intriguing."
    "Studying computer vision is exciting."
    "Natural language processing is a fascinating domain."
    "I enjoy coding in Python for data science projects."
    "Building models is a creative process."
    "I love experimenting with different machine learning techniques."
    "The potential of AI to transform industries is amazing."
    "I enjoy staying updated with the latest tech trends."
    "Learning about reinforcement learning is interesting."
    "I find predictive modeling to be very useful."
    "I love solving problems with data analysis."
    "Data preprocessing is a crucial step in machine learning."
    "I enjoy reading research papers on deep learning."
    "I find optimization techniques fascinating."
    "Understanding algorithms helps in developing better solutions."
    "I love the challenge of debugging code."
    "Machine learning applications are diverse and impactful."
    "I enjoy collaborating with others on tech projects."
    "Learning new programming languages is fun."
    "I love working with large datasets."
    "I find feature engineering to be an art."
    "Model evaluation is an essential part of machine learning."
    "I enjoy attending tech conferences."
    "Learning about big data technologies is exciting."
    "I love experimenting with neural network architectures."
    "I find the theory behind machine learning algorithms interesting."
    "I enjoy visualizing data insights."
    "Machine learning models can make accurate predictions."
    "I love the creativity involved in data storytelling."
    "I find unsupervised learning techniques intriguing."
    "I enjoy automating tasks with AI."
    "Learning about AI ethics is important."
    "I love the problem-solving aspect of machine learning."
    "I find cloud computing technologies fascinating."
    "I enjoy using machine learning for real-world applications."
    "I love experimenting with different data preprocessing techniques."
    "I find transfer learning to be a powerful approach."
    "I enjoy working on machine learning projects."
    "Learning about data privacy is crucial."
    "I love the innovation happening in the AI field."
    "I find data visualization tools useful."
    "I enjoy testing and validating machine learning models."
    "I love discovering new machine learning applications."
    "I find ensemble methods to be effective."
    "I enjoy learning from data."
    "Machine learning can provide valuable insights."
    "I love the interdisciplinary nature of AI."
    "I find recommendation systems interesting."
    "I enjoy participating in hackathons."
    "Learning about neural networks is fascinating."
    "I love the potential of AI to solve complex problems."
    "I find sentiment analysis intriguing."
    "I enjoy implementing machine learning algorithms."
    "I love the excitement of discovering patterns in data."
    "I find time series analysis challenging."
    "I enjoy exploring different types of data."
    "Machine learning is transforming various industries."
    "I love working on predictive analytics."
    "I find anomaly detection to be useful."
    "I enjoy studying the mathematics behind machine learning."
    "I love the hands-on experience of building models."
    "I find clustering techniques interesting."
    "I enjoy exploring open-source machine learning libraries."
    "Machine learning can automate complex tasks."
    "I love the flexibility of machine learning models."
    "I find computer vision applications fascinating."
    "I enjoy solving real-world problems with AI."
    "I love the continuous learning aspect of AI."
    "I find reinforcement learning to be challenging."
    "I enjoy experimenting with hyperparameter tuning."
    "Machine learning can improve decision-making processes."
    "I love the creativity involved in feature selection."
    "I find generative models to be fascinating."
    "I enjoy reading about the latest AI advancements."
    "Machine learning can enhance user experiences."
    "I love the diversity of machine learning applications."
    "I find natural language generation intriguing."
    "I enjoy working with text data."
    "Machine learning can optimize business processes."
    "I love the innovation in AI research."
    "I find the concept of machine learning interpretability interesting."
    "I enjoy creating machine learning workflows."
    "Machine learning can uncover hidden patterns."
    "I love the impact of AI on society."
    "I find deep reinforcement learning fascinating."
    "I enjoy developing custom machine learning solutions."
    "Machine learning can improve customer experiences."
    "I love the potential of AI in healthcare."
    "I find the scalability of machine learning models intriguing."
    "I enjoy applying machine learning to finance."
    "Machine learning can enhance security measures."
    "I love the possibilities of AI in creative industries."
    "I find the ethical implications of AI important."
    "I enjoy sharing knowledge about machine learning."
]

# Tokenization and Preprocessing of Data

In [13]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

total_words = len(tokenizer.word_index) + 1

input_sequences = []

for line in sentences:
  token_list  = tokenizer.texts_to_sequences([line])[0]

  for  i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i + 1]
    input_sequences.append(n_gram_sequence)

mak_sequence_len = max([len(x) for x in input_sequences])

input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

In [14]:
X = input_sequences[:, :-1]

y = input_sequences[:, -1]

y = tf.keras.utils.to_categorical(y, num_classes=total_words)

# Defining the LSTM Model

In [15]:
# Define the LSTM model

# Sequential model allows stacking layers in a linear fashion
model = Sequential([
    # Embedding layer: Converts word indices to dense vectors
    # Input dimension: total number of words, Output dimension: size of embedding vectors
    # Input length: length of input sequences (excluding the last word)
    Embedding(total_words, 10, input_length=max_sequence_len-1),

    # LSTM layer with 30 units
    # LSTM (Long Short-Term Memory) is a type of RNN that can capture long-term dependencies
    LSTM(100),

    # Dense output layer with a softmax activation function
    # Output dimension: total number of words (for multi-class classification)
    # Softmax activation converts the output to probabilities for each word
    Dense(total_words, activation='softmax')
])


# Compiling the model

In [16]:

# Compile the model

# Compile the model specifies the loss function, optimizer, and evaluation metrics
model.compile(
    # Loss function: Categorical cross-entropy, used for multi-class classification problems
    loss='categorical_crossentropy',

    # Optimizer: Adam, an efficient optimization algorithm that adjusts the learning rate during training
    optimizer='adam',

    # Metrics: Accuracy, to evaluate the model's performance during training and testing
    metrics=['accuracy']
)



# Training the Model

In [17]:

# Train the model

# Fit the model on the training data
# X: Input sequences
# y: One-hot encoded labels
# epochs: Number of times the model will go through the entire dataset
# verbose: Controls the verbosity of the output during training (1 for progress bar)
model.fit(X, y, epochs=50, verbose=1)



Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 14s 524ms/step - accuracy: 0.0645 - loss: 5.3658
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 20s 545ms/step - accuracy: 0.1177 - loss: 4.6673
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 12s 546ms/step - accuracy: 0.0941 - loss: 4.5564
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 11s 488ms/step - accuracy: 0.1013 - loss: 4.5590
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 11s 489ms/step - accuracy: 0.0936 - loss: 4.4557
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 21s 530ms/step - accuracy: 0.1017 - loss: 4.5228
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 20s 511ms/step - accuracy: 0.1205 - loss: 4.4039
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 11s 461ms/step - accuracy: 0.1094 - loss: 4.5016
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 21s 526ms/step - accuracy: 0.0987 - loss: 4.4956
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 12s 538ms/step - accuracy: 0.1166 - loss: 4.4680
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 19s 489ms/step - accuracy: 0.1688 - loss: 4.3419
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 21

# Prediction of Next Word

In [18]:
# Function to predict the next word(s) given a seed text
def predict_next_word(seed_text, next_words=2):
    # Repeat the prediction process for the specified number of next words
    for _ in range(next_words):
        # Convert the seed text into a sequence of integers using the tokenizer
        token_list = tokenizer.texts_to_sequences([seed_text])[0]

        # Pad the sequence to ensure it matches the input length expected by the model
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

        # Predict the probabilities of the next word in the sequence
        predicted = model.predict(token_list, verbose=0)

        # Get the index of the word with the highest probability
        predicted_word_index = np.argmax(predicted, axis=-1)[0]

        # Retrieve the word corresponding to the predicted index
        predicted_word = tokenizer.index_word[predicted_word_index]

        # Append the predicted word to the seed text
        seed_text += " " + predicted_word

    # Return the updated seed text with the predicted word(s)
    return seed_text


In [19]:
# Test prediction
print(predict_next_word("Machine Learning can improve"))

Machine Learning can improve fascinating i
