# How to install numpy?
!pip install numpy

In [2]:
# import the numpy package as np
import numpy as np

Python Numpy Array v/s list
we use python numpy array instead of a list because of the below three reasons:
1. Less Memory
2. Fast
3. Convenient

In [7]:
# Create 2 new lists height and weight
person_height = [5.2 ,5.4, 5.5]
person_weight = [43, 34, 45, 67]

# Create 2 numpy arrays from height and weight
person_height = np.array(person_height)
person_weight = np.array(person_weight)

In [8]:
# Print 'person_height' array
person_height

array([5.2, 5.4, 5.5])

In [9]:
# Print 'person_weight' array
person_weight

array([43, 34, 45, 67])

In [10]:
# Print type of 'person_height'
print(type(person_weight))

<class 'numpy.ndarray'>


# 2. Indexing an Array

Intexing in 1 dimension

In [11]:
# Given array
my_array = np.array([11, 22, 33, 45, 34,67])
print(my_array)

[11 22 33 45 34 67]


Each element in the array can be accessed by passing the positional index of the element.

In [12]:
# Get the 1st element 
# indexing starts from '0'
print(my_array[0])

# Get the thier element
print(my_array[2])

11
33


Indexing in 2 dimensions

In [13]:
my_array = np.array([[102, 123, 234],
                    [34, 56, 367],
                    [543, 34, 67]])
my_array

array([[102, 123, 234],
       [ 34,  56, 367],
       [543,  34,  67]])

We can retrieve an element of the 2D array using two indices i and j - i 
selects the row,  and j selects the column:

In [14]:
# get the element in 3rd row and 2nd column
print(my_array[2, 1])

34


In [17]:
# we can pass ith row and jth column in separate brakets([])
print(my_array[2][1])

34


# Picking a row or column
we can also select a single row or column

In [18]:
# Pick the second row from the array
print(my_array[2])

[543  34  67]


In [19]:
# Pick the second column from the array
print(my_array[:,2])

[234 367  67]


# 3. Slicing Array
Slicing a 1D array

In [20]:
my_array = [103, 235, 232, 453, 133]

In [21]:
# Pick the second , third, and fourth element from the array
new_array = my_array[1:4]
new_array

[235, 232, 453]

The slice notation specifies a start and end value [start:end], where 'start'
is inclusive but 'end' is exclusive.

In [23]:
# First three elements
c = my_array[:3]
c

[103, 235, 232]

In [24]:
# All the elements from 235
d = my_array[2:]
d

[232, 453, 133]

In [26]:
# get the complete array
e = my_array[:]
e

[103, 235, 232, 453, 133]

In [31]:
my_array = np.array([[102, 123, 234 , 45],
                     [34,  56, 367, 57],
                     [543, 34, 67, 89],
                     [67,  65, 56, 90]])
my_array

array([[102, 123, 234,  45],
       [ 34,  56, 367,  57],
       [543,  34,  67,  89],
       [ 67,  65,  56,  90]])

In [32]:
# Select all rows except 1st
# Select 3rd and 4th column
print(my_array[1:,2:4])

[[367  57]
 [ 67  89]
 [ 56  90]]


 Note : The index returns an element of the array, the slice returns a list of 
 elements.

# 4. Operations on a Array

In [33]:
my_array1 = np.array([120, 230 , 320 , 456, 453])
my_array2 = np.arange(5)

In [34]:
my_array2

array([0, 1, 2, 3, 4])

Add the two arrays

In [35]:
my_array3 = my_array1 + my_array2
my_array3

array([120, 231, 322, 459, 457])

In [36]:
# Multiply each element in the array by 4
my_array1 * 4

array([ 480,  920, 1280, 1824, 1812])

Use '**' to compute power of the numbers.

In [37]:
# get square of each element
my_array1 ** 2

array([ 14400,  52900, 102400, 207936, 205209])

Using Numpy with Comparison Expression

In [39]:
my_array = np.array([34, 56, 56, 23, 20 ])

# Check which elements are greater than or equal to 40
# the comparison condition gives boolean output
new_array = my_array >= 40
new_array

array([False,  True,  True, False, False])

Pass the above boolean array to the main array to fetch the values that satisfy
the comparison condition.

In [40]:
# elements greater than or equal to 40
my_array[new_array]

array([56, 56])

Rather than creating a separate array of booleans , you can specify the comparsion operation directly on the main array.

# 5. Arithmetic Functions in Numpy

In [41]:
# Given array
my_array = np.array([5,6,3,6,8])
my_array

array([5, 6, 3, 6, 8])

Sum():
sum() function adds all the values in the array and gives a scalar output.

In [42]:
np .sum(my_array)

28

In [43]:
# add all the elements of 'my_array'
my_array.sum()

28

min():
min function finds the lowest value in the array.

In [44]:
# find minimum of 'my_array'
my_array.min()

3

Power():
power function raises the numbers in the array to the given value.


In [ ]:
my_array ** 3

In [45]:
# get cube of element of 'mY_array'
np.power(my_array,3)

array([125, 216,  27, 216, 512], dtype=int32)

# 6. Concatenation of Array
The arrays can be concatenated only if they have same shape, except in the dimension corresponding to the axis of concatenation.

Concatenate 1D array

In [46]:
# concatenate two ID arrays
array_x = np.array([11, 33, 45])
array_y = np.array([34, 23, 15])
np.concatenate([array_x, array_y])

array([11, 33, 45, 34, 23, 15])

You can also concatenate more than two arrays at once.

In [47]:
array_z = np.array([67,93])
print(np.concatenate([array_x, array_y, array_z]))

[11 33 45 34 23 15 67 93]


Concatenate 2D array


In [4]:
# Create a 2D array
my_array = np.array([[1,2,3],
                     [4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

concatenate along the first axis

In [5]:
# by default concatenate() is along 'axis = 0'
np.concatenate([my_array, my_array], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Concatenate along the second axis

In [6]:
np.concatenate([my_array, my_array], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Concatenate 1D and 2D array

In [7]:
# Concatenate the ID and 2D arrays
# Consider a ID array -- 'array_x'
# Consider a 2D array -- 'array_y'
np.concatenate((array_x, my_array), axis = 0)

NameError: name 'array_x' is not defined

Note : One can not concatenate the arrays with different dimensions.

# 7. Splitting of Array
Splitting is used to split the array into multiple sub-arrays. It is opposite of concatenation, which is implemented by the functions like split(), hsplit(),
and son on.
split():

In [11]:
# split the array into sub_arrays it means to diving array
array_x = np.arange(8)
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

Split the 1D array at positions indicated

In [12]:
# the split occurs at 5th and 7th indices
array_y = np.split(array_x,[5,7])
print(array_y)

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]


# VSplit():
The vsplit() function is used to split an array into multiple sub-arrays 
vertically (row-wise).

In [13]:
my_array = np.arange(20.0).reshape(4,5)
my_array

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [17]:
np.vsplit(my_array, 2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]),
 array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

# hsplit():
The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise).

In [18]:
my_array = np.arange(16.0).reshape(4,4)
my_array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [19]:
np.hsplit(my_array, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]